name: Tests

on: push

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: ludeeus/action-shellcheck@2.0.0
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
        env:
          API_KEY: ${{ secrets.AXE_WATCHER_API_KEY }}
          SERVER_URL: ${{ secrets.SERVER_URL }}
      - run: yarn && yarn test
  axe-dev-hub:
    runs-on: ubuntu-latest
    needs: cypress
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          api_key: ${{ secrets.AXE_WATCHER_API_KEY }}
          server_url: ${{ secrets.SERVER_URL }}
