name: Tests

on:
  workflow_dispatch

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: ludeeus/action-shellcheck@2.0.0
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dequelabs/axe-api-team-public/.github/actions/create-project-issue-v1@148f5d08522700d82ec75e546f54bb77b23150b5
        with:
          github_token: ${{ github.token }}
          title: 'I am a new issue, hazaar!'
          body: 'I am new issue body, also hazaar!'
          project_id: 1
          
          
          
  #     - name: Run tests
  #       run: xvfb-run --auto-servernum yarn && yarn test
  #       env:
  #         API_KEY: ${{ secrets.AXE_WATCHER_API_KEY }}
  #         SERVER_URL: ${{ secrets.SERVER_URL }}
  # axe-dev-hub:
  #   runs-on: ubuntu-latest
  #   needs: cypress
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: dequelabs/axe-devhub-action@e5179b2bb07a1a9af15a827bdaaa4da5ee47bf22
  #       with:
  #         api_key: ${{ secrets.AXE_WATCHER_API_KEY }}
  #         server_url: ${{ secrets.SERVER_URL }}
  #         enable_a11y_threshold: "true"
